# Generated by Django 5.0.1 on 2024-01-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_model',
            new_name='Aplication',
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credential.district')),
            ],
        ),
    ]
