# Generated by Django 5.0.1 on 2024-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0006_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('account_type', models.CharField(max_length=70)),
                ('district', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('materials', models.TextField()),
            ],
        ),
    ]
