# Generated by Django 5.0.1 on 2024-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0007_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
